#ifndef __ZE_OPTICK_PROFILER_H__
#define __ZE_OPTICK_PROFILER_H__

#include "Dependencies/Optick_1.3.1/src/optick.h"

#define ZE_PROFILER_INIT(APP_NAME) // TODO

#define ZE_PROFILER_DESTROY() // TODO

#define ZE_PROFILER_FRAME(FRAME_NAME) OPTICK_FRAME(FRAME_NAME)

#define ZE_PROFILER_THREAD(THREAD_NAME) OPTICK_THREAD(THREAD_NAME)

#define ZE_PROFILER_FUNCTION(FUNC_NAME) OPTICK_EVENT(FUNC_NAME)

#define ZE_PROFILER_SECTION(SECTION_NAME) OPTICK_EVENT(SECTION_NAME)

#endif
